# From: https://goreleaser.com/ci/actions/#usage
name: release

env:
  GO111MODULE: on

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: "1.17.5"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.6.0
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
